Lp.Coriander/Lp.Coriander.Web/Controllers/DashboardController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace Lp.Coriander.Web.Controllers
{
    public class DashboardController : Controller
    {
        // GET: Dashboard
        public ActionResult Index()
        {
            return View();
        }
    }
}

Lp.Coriander/Lp.Coriander.Web/Controllers/MenuController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace Lp.Coriander.Web.Controllers
{
    public class MenuController : Controller
    {
        // GET: Menu
        [ChildActionOnly]
        public ActionResult AppSideMenu()
        {
            return PartialView("Menu/AppSideMenu");
        }
    }
}

Lp.Coriander/Lp.Coriander.Web/Controllers/NotificationController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace Lp.Coriander.Web.Controllers
{
    public class NotificationController : Controller
    {
        // GET: Notification
        public ActionResult Index()
        {
            return View();
        }
    }
}

Lp.Coriander/Lp.Coriander.Web/Controllers/UserController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace Lp.Coriander.Web.Controllers
{
    public class UserController : Controller
    {
        // GET: User
        public ActionResult Index()
        {
            return View();
        }

        public ActionResult ManageProfile()
        {
            return View();
        }

        [ChildActionOnly]
        public ActionResult Notifications()
        {
            return PartialView("User/Notifications");
        }

        [ChildActionOnly]
        public ActionResult UserInfo()
        {
            return PartialView("User/UserInfo");
        }


    }
}

Lp.Coriander/Lp.Coriander.Web/Views/Shared/_Layout.cshtml
<html>
<head>
    <title>Coriander  || @ViewBag.Title</title>

    <!-- Meta -->
    <meta charset="UTF-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0, user-scalable=0, minimum-scale=1.0, maximum-scale=1.0">
    <meta name="apple-mobile-web-app-capable" content="yes">
    <meta name="apple-mobile-web-app-status-bar-style" content="black">
    <meta http-equiv="X-UA-Compatible" content="IE=9; IE=8; IE=7; IE=EDGE" />
    <link rel="shortcut icon" href="/favicon.ico?=v2" />

    @Styles.Render("~/Styles/appcss")


    <!-- END CSS TEMPLATE -->
    @RenderSection("controlCss", false)


</head>
<!-- BEGIN BODY -->
<body class="">
    <!-- BEGIN HEADER -->
    <div class="header navbar navbar-inverse ">
        <!-- BEGIN TOP NAVIGATION BAR -->
        <div class="navbar-inner">
            <div class="header-seperation">
                <ul class="nav pull-left notifcation-center" id="main-menu-toggle-wrapper" style="display:none">
                    <li class="dropdown"> <a id="main-menu-toggle" href="#main-menu" class=""> <div class="iconset top-menu-toggle-white"></div> </a> </li>
                </ul>
                <!-- BEGIN LOGO -->
                <a href="@Url.Action("index","Dashboard")"><img src="/Content/Admin/img/logo.png" class="logo" alt="" data-src="/Content/Admin/img/logo.png" data-src-retina="/Content/Admin/img/logo.png" height="24" /></a>
                <!-- END LOGO -->
                <ul class="nav pull-right notifcation-center">
                    <li class="dropdown" id="header_task_bar"> <a href="@Url.Action("index","Dashboard")" class="dropdown-toggle active" data-toggle=""> <div class="iconset top-home"></div> </a> </li>
                    @if (ViewBag.RightMenu == "True")
                    {
                        <li class="dropdown" id="header_rightmenu_bar">
                            <a id="chat-menu-toggle" href="#sidr" class="chat-menu-toggle"><div class="iconset top-menu-toggle-dark "></div></a>
                        </li>
                    }
                </ul>

            </div>
            <!-- END RESPONSIVE MENU TOGGLER -->
            <div class="header-quick-nav">
                <!-- BEGIN TOP NAVIGATION MENU -->
                <div class="pull-left">
                    <ul class="nav quick-section">
                        <li class="quicklinks">
                            <a href="#" class="" id="layout-condensed-toggle">
                                <div class="iconset top-menu-toggle-dark"></div>
                            </a>
                        </li>
                    </ul>
                    <ul class="nav quick-section"></ul>
                </div>
                <!-- END TOP NAVIGATION MENU -->
                <!-- BEGIN CHAT TOGGLER -->
                <div class="pull-right">

                    <ul class="nav quick-section ">
                        <li class="quicklinks">
                            <a data-toggle="dropdown" class="dropdown-toggle  pull-right " href="#" id="user-options">
                                <div class="iconset top-settings-dark "></div>
                            </a>
                            <ul class="dropdown-menu  pull-right" role="menu" aria-labelledby="user-options">
                                <li>
                                    <a href="@Url.Action("ManageProfile", "User")"> My Account</a>
                                </li>

                                <li>
                                    <a href="@Url.Action("Index","Notification")">
                                        Notifications&nbsp;&nbsp;
                                        @{ Html.RenderAction("Notifications", "User", new { area = "" }); }
                                    </a>
                                </li>
                                <li class="divider"></li>
                                @using (Html.BeginForm("LogOff", "Account", new { area = "" }, FormMethod.Post, new { id = "logoutForm" }))
                                {
                                    @Html.AntiForgeryToken()
                                    <li><a id="logoff"><i class="fa fa-power-off"></i>&nbsp;&nbsp;Log Out</a></li>

                                }


                            </ul>

                        </li>
                        @if (ViewBag.RightMenu == "True")
                        {
                            <li class="quicklinks">
                                <a id="chat-menu-toggle" href="#sidr" class="chat-menu-toggle"><div class="iconset top-menu-toggle-dark "></div></a>
                            </li>
                        }
                    </ul>
                </div>
                <!-- END CHAT TOGGLER -->
            </div>
            <!-- END TOP NAVIGATION MENU -->

        </div>
        <!-- END TOP NAVIGATION BAR -->
    </div>

    <!-- END HEADER -->
    <!-- BEGIN CONTAINER -->
    <div class="page-container row">
        <!-- BEGIN SIDEBAR -->
        <div class="page-sidebar" id="main-menu">
            <div class="page-sidebar-wrapper" id="main-menu-wrapper">
                <!-- BEGIN MINI-PROFILE -->
                <div class="user-info-wrapper">

                    <div class="user-info">
                        <div class="greeting">Welcome</div>
                        @{ Html.RenderAction("UserInfo", "User", new { area = "" }); }


                    </div>
                </div>
                <!-- END MINI-PROFILE -->
                <!-- BEGIN SIDEBAR MENU -->
                <p class="menu-title"> <span class="pull-right"></span></p>

                @{ Html.RenderAction("AppSideMenu", "Menu", new { area = "", selected = ViewBag.SelectedMenu }); }
                <div class="clearfix"></div>

            </div>
            <a href="#" class="scrollup">Scroll</a>
            <div class="clearfix"></div>
            <!-- END SIDEBAR MENU -->
        </div>
        <div class="footer-widget">
            <div class="progress transparent progress-small no-radius no-margin">
                <div class="progress-bar progress-bar-success animate-progress-bar" data-percentage="79%" style="width: 79%;"></div>
            </div>
            <div class="pull-right">
                <div class="details-status">
                    <span class="animate-number" data-value="86" data-animation-duration="560">86</span>%
                </div>

                @using (Html.BeginForm("LogOff", "Account", new { area = "" }, FormMethod.Post, new { id = "logoutForm" }))
                {
                    @Html.AntiForgeryToken()
                    <a id="logoffBottom"><i class="fa fa-power-off"></i></a>

                }
            </div>
        </div>
        <!-- END SIDEBAR -->
        <!-- BEGIN PAGE CONTAINER-->
        <div class="page-content">

            <div class="content">
                @RenderBody()

            </div>
        </div>
        @RenderSection("RightMenu", false)
        <!-- END CONTAINER -->
    </div>



    @Scripts.Render("~/bundles/app")

    <script>
        @if (TempData["SuccessMessage"] != null)
        {
            <text>
        Messenger().post(
            {

                type:'success',
                message: '@TempData["SuccessMessage"]',
                showCloseButton:                true,
            });
        </text>
        }
    @if (TempData["ErrorMessage"] != null)
        {
            <text>
    Messenger().post(
        {
            type: 'error',
            message:  '@TempData["ErrorMessage"]',
            showCloseButton:            true,
        });
    </text>
        }
    </script>
   

    <!-- END PAGE LEVEL PLUGINS   -->
    <script src="/Content/Admin/js/form_elements.js" type="text/javascript"></script>
    <!-- PAGE JS -->
    @RenderSection("scripts", false)
    @RenderSection("controlScripts", false)
    <!-- BEGIN CORE TEMPLATE JS -->
    <script src="/Content/Admin/js/core.js" type="text/javascript"></script>
    <script src="/Content/Admin/js/chat.js" type="text/javascript"></script>




    <!-- END CORE TEMPLATE JS -->
</body>
</html>